### ISSUE TITLE
workflow-aggregator - java.io.IOException

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/core#159]
This might be related to dependencies:

```
==> default: Installing workflow-aggregator from update center
==> default: May 22, 2017 11:12:28 AM hudson.cli.CLI$5 run
==> default: WARNING: null
==> default: java.io.IOException: Stream is closed
==> default:     at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3512)
==> default:     at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3486)
==> default:     at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
==> default:     at hudson.cli.PlainCLIProtocol$EitherSide.send(PlainCLIProtocol.java:175)
==> default:     at hudson.cli.PlainCLIProtocol$ClientSide.sendEndStdin(PlainCLIProtocol.java:347)
==> default:     at hudson.cli.CLI$5.run(CLI.java:671)
```

check if related to: http://stackoverflow.com/questions/34722609/error-when-installing-jenkins-workflow-plugin

check if happening in prod

spotted in vagrant

**Comment by styk-tv** [comment]
in different place now...
```
==> default: Installing ssh-credentials from update center
==> default: May 22, 2017 1:30:01 PM hudson.cli.CLI$5 run
==> default: WARNING: null
==> default: java.io.IOException: Stream is closed
==> default: 	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3512)
==> default: 	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3486)
==> default: 	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
==> default: 	at hudson.cli.PlainCLIProtocol$EitherSide.send(PlainCLIProtocol.java:175)
==> default: 	at hudson.cli.PlainCLIProtocol$ClientSide.sendEndStdin(PlainCLIProtocol.java:347)
==> default: 	at hudson.cli.CLI$5.run(CLI.java:671)
```
