### ISSUE TITLE
backup/restore - remove dependency on redis

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/core#163]
any time app launch fail occurs, registration job has to be re-run to correct failed redis database gone missing.

1. this has to survive failure
2. we must disconnect this from redis and into a simple yaml file (for storage of applications)

```
2017-05-23 09:07:42,854 [INFO] madcore.cmds.configure: Restore backup for redis
2017-05-23 09:07:53,189 [INFO] madcore.cmds.configure: cp: cannot create regular file '/hab/svc/redis/data/dump.rdb': No such file or directory
2017-05-23 09:07:53,189 [INFO] madcore.cmds.configure: Done.
2017-05-23 09:07:58,241 [INFO] madcore.cmds.configure: Reconfigure HaProxy
2017-05-23 09:08:02,285 [INFO] madcore.cmds.configure: Traceback (most recent call last):
2017-05-23 09:08:02,285 [INFO] madcore.cmds.configure: File "/opt/madcore/bin/haproxy_get_ssl.py", line 20, in <module>
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: check = r_server.get("need_CSR")
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: return self.execute_command('GET', name)
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: connection.send_command(*args)
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: self.send_packed_command(self.pack_command(*args))
2017-05-23 09:08:02,286 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: self.connect()
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: raise ConnectionError(self._error_message(e))
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: Done.
2017-05-23 09:08:02,287 [INFO] madcore.cmds.configure: Finished: SUCCESS
2017-05-23 09:08:02,331 [INFO] madcore.cmds.configure: Successful madcore restore.
```

**Comment by styk-tv** [comment]
move habitat to plugins, remove all traces of redis, habitat, depot from installation files

need to make sure yaml is not destroyed by any job failures so do not delete until  you know you have new one etc...
