### ISSUE TITLE
restore fail

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/core#48]
```
_  _ ____ ___  ____ ____ ____ ____    ___  ____ ____ _  _ _  _ ___
|\/| |__| |  \ |    |  | |__/ |___    |__] |__| |    |_/  |  | |__]
|  | |  | |__/ |___ |__| |  \ |___    |__] |  | |___ | \_ |__| |


2017-01-30 09:15:47,404 [INFO] madcore.cmds.configure: Madcore Backup
2017-01-30 09:15:47,404 [INFO] madcore.cmds.configure: [madcore.restore] Job input parameter.
+--------------+------------------------------------------+
| Name         | Value                                    |
+--------------+------------------------------------------+
| S3BucketName | madcore-s3-madcores3bucket-1qo68jlb5yyit |
+--------------+------------------------------------------+


2017-01-30 09:15:48,563 [INFO] madcore.cmds.configure: [madcore.restore] Build job.
2017-01-30 09:15:48,564 [INFO] madcore.cmds.configure: Get console output for job: 'madcore.restore #1'
2017-01-30 09:15:48,870 [ERROR] madcore.cmds.configure: [madcore.restore] Error while reading job[madcore.restore] number[1]. Retry: 1
2017-01-30 09:15:54,599 [INFO] madcore.cmds.configure: [madcore.restore] Build job.
2017-01-30 09:15:54,599 [INFO] madcore.cmds.configure: Get console output for job: 'madcore.restore #1'
2017-01-30 09:15:54,890 [ERROR] madcore.cmds.configure: [madcore.restore] Error while reading job[madcore.restore] number[1]. Retry: 2
2017-01-30 09:16:00,162 [INFO] madcore.cmds.configure: [madcore.restore] Job already running.
2017-01-30 09:16:00,163 [INFO] madcore.cmds.configure: Get console output for job: 'madcore.restore #1'
2017-01-30 09:16:00,536 [INFO] madcore.cmds.configure: Started by user anonymous
2017-01-30 09:16:00,537 [INFO] madcore.cmds.configure: Started by user anonymous
2017-01-30 09:16:00,537 [INFO] madcore.cmds.configure: Building in workspace /var/lib/jenkins/workspace/madcore.restore
2017-01-30 09:16:00,538 [INFO] madcore.cmds.configure: [madcore.restore] $ /bin/bash /tmp/hudson4910580556707707930.sh
2017-01-30 09:16:00,538 [INFO] madcore.cmds.configure: Restore from S3 : madcore-s3-madcores3bucket-1qo68jlb5yyit
download: s3://madcore-s3-madcores3bucket-1qo68jlb5yyit/backup/certs/server.csr to ../../../../../opt/backup/certs/server.csr
download: s3://madcore-s3-madcores3bucket-1qo68jlb5yyit/backup/redis/dump.rdb to ../../../../../opt/backup/redis/dump.rdb
download: s3://madcore-s3-madcores3bucket-1qo68jlb5yyit/backup/certs/openssl.cnf to ../../../../../opt/backup/certs/openssl.cnf
download: s3://madcore-s3-madcores3bucket-1qo68jlb5yyit/backup/certs/server.bundle.pem to ../../../../../opt/backup/certs/server.bundle.pem
download: s3://madcore-s3-madcores3bucket-1qo68jlb5yyit/backup/certs/server.key to ../../../../../opt/backup/certs/server.key
2017-01-30 09:16:07,028 [INFO] madcore.cmds.configure: Restore backup for redis
2017-01-30 09:16:17,798 [INFO] madcore.cmds.configure: cp: cannot create regular file '/hab/svc/redis/data/dump.rdb': No such file or directory
2017-01-30 09:16:17,798 [INFO] madcore.cmds.configure: Failed to start habitat-depot.service: Unit habitat-depot.service not found.
2017-01-30 09:16:17,799 [INFO] madcore.cmds.configure: Done.
2017-01-30 09:16:22,141 [INFO] madcore.cmds.configure: Reconfigure HaProxy
2017-01-30 09:16:23,319 [INFO] madcore.cmds.configure: Traceback (most recent call last):
2017-01-30 09:16:23,319 [INFO] madcore.cmds.configure: File "/opt/madcore/bin/haproxy_get_ssl.py", line 14, in <module>
2017-01-30 09:16:23,320 [INFO] madcore.cmds.configure: check = r_server.get("need_CSR")
2017-01-30 09:16:23,320 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
2017-01-30 09:16:23,320 [INFO] madcore.cmds.configure: return self.execute_command('GET', name)
2017-01-30 09:16:23,320 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
2017-01-30 09:16:23,321 [INFO] madcore.cmds.configure: connection.send_command(*args)
2017-01-30 09:16:23,321 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
2017-01-30 09:16:23,321 [INFO] madcore.cmds.configure: self.send_packed_command(self.pack_command(*args))
2017-01-30 09:16:23,321 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
2017-01-30 09:16:23,322 [INFO] madcore.cmds.configure: self.connect()
2017-01-30 09:16:23,322 [INFO] madcore.cmds.configure: File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
2017-01-30 09:16:23,322 [INFO] madcore.cmds.configure: raise ConnectionError(self._error_message(e))
2017-01-30 09:16:23,323 [INFO] madcore.cmds.configure: redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
2017-01-30 09:16:23,323 [INFO] madcore.cmds.configure: Done.
2017-01-30 09:16:23,323 [INFO] madcore.cmds.configure: Finished: SUCCESS
2017-01-30 09:16:23,418 [INFO] madcore.cmds.configure: Successful madcore restore.
```

**Comment by styk-tv** [comment]
+ false positive.

**Comment by styk-tv** [comment]
```
sudo hab pkg binlink core/hab-depot bldr-depot
```
above binary is not hab-depot but bldr-depot instead


```
sudo bash "/opt/madcore/registryhabitat/setup.sh"
```
above is starting redis as well, needs to be moved before jenkins runs restore job. otherwise no redis to restore to.

**Comment by botzill** [comment]
What is the scenario that we have this? I just did rebuild with restore and all was OK. By default when we core is created habitat is started and all the paths are created(including one for redis). When I do restore I should already have habitat service available and doing a ``systemctl start habitat-depot`` is enough, no?
