### ISSUE TITLE
kubernetes dashboard doesn't start

### ISSUE THREAD

**Issue by hantden** [madcore-ai/core#58]
2017-01-30 16:15:59,715 [INFO] madcore.cmds.selftest: Starting building: madcore.selftest.kubedash #1
2017-01-30 16:15:59,937 [INFO] madcore.cmds.selftest:     Started by upstream project "madcore.selftest" build number 1
2017-01-30 16:15:59,937 [INFO] madcore.cmds.selftest:     originally caused by:
2017-01-30 16:15:59,937 [INFO] madcore.cmds.selftest:     Started by user anonymous
2017-01-30 16:15:59,937 [INFO] madcore.cmds.selftest:     Building in workspace /var/lib/jenkins/workspace/madcore.selftest.kubedash
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     [WS-CLEANUP] Deleting project workspace...
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     [madcore.selftest.kubedash] $ /bin/bash /tmp/hudson8781112211201378948.sh
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     /opt/madcore/jenkins/selftests ~/workspace/madcore.selftest.kubedash
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     sterted testing kubernetes dashboard
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     kubernetes dashboard down
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2017-01-30 16:15:59,938 [INFO] madcore.cmds.selftest:     Dload  Upload   Total   Spent    Left  Speed
100   265  100   265    0     0  33891      0 --:--:-- --:--:-- --:--:-- 37857  0     0      0      0 --:--:-- --:--:-- --:--:--     0
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     {
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     "kind": "Status",
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     "apiVersion": "v1",
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     "metadata": {},
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     "status": "Failure",
2017-01-30 16:15:59,939 [INFO] madcore.cmds.selftest:     "message": "endpoints \"kubernetes-dashboard\" not found",
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     "reason": "NotFound",
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     "details": {
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     "name": "kubernetes-dashboard",
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     "kind": "endpoints"
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     },
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     "code": 404
2017-01-30 16:15:59,940 [INFO] madcore.cmds.selftest:     }BASH FAILED WITH POSITIVE CODE. FORCING JENKINS BASH EXIT AS -1 (TO SHOW THE FAIL)
2017-01-30 16:15:59,941 [INFO] madcore.cmds.selftest:     Build step 'Execute shell' marked build as failure
2017-01-30 16:15:59,941 [INFO] madcore.cmds.selftest:     Finished: FAILURE
2017-01-30 16:15:59,941 [INFO] madcore.cmds.selftest: [Pipeline] }
2017-01-30 16:15:59,941 [INFO] madcore.cmds.selftest: [Pipeline] // node
2017-01-30 16:15:59,941 [INFO] madcore.cmds.selftest: [Pipeline] End of Pipeline
2017-01-30 16:15:59,942 [INFO] madcore.cmds.selftest: ERROR: madcore.selftest.kubedash #1 completed with status FAILURE (propagate: false to ignore)
2017-01-30 16:15:59,942 [INFO] madcore.cmds.selftest: Finished: FAILURE
2017-01-30 16:16:00,059 [ERROR] madcore: 'NoneType' object has no attribute '__getitem__'
2017-01-30 16:16:00,059 [DEBUG] madcore: Got an error: 'NoneType' object has no attribute '__getitem__'
2017-01-30 16:16:00,064 [DEBUG] madcore: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/cliff-2.4.0-py2.7.egg/cliff/command.py", line 90, in run
    return self.take_action(parsed_args) or 0
  File "/usr/local/lib/python2.7/site-packages/madcore-0.3.7.29+gab88154-py2.7.egg/madcore/libs/commands.py", line 19, in take_action
    self.jenkins_run_job_show_output(self.job_name, parameters=self.job_parameters)
  File "/usr/local/lib/python2.7/site-packages/madcore-0.3.7.29+gab88154-py2.7.egg/madcore/base.py", line 710, in jenkins_run_job_show_output
    return job_info['lastSuccessfulBuild']['number'] == build_number
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by botzill** [comment]
This issue is related to CLI project. Please make sure next time you post the issue on that repo because I can easily reference issue id in commits and have features like automatically close an issue and so on. Thx.

**Comment by botzill** [comment]
Fixed this, PR on CLI repo.
