### ISSUE TITLE
expired creds do not fail the app

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/core#62]
example of failed credentials on destroy above. this should not attempt to run at all when failing

```
2017-01-30 22:11:24,441 [INFO] madcore.cmds.destroy: Destroy
2017-01-30 22:11:24,895 [ERROR] madcore: An error occurred (InvalidClientTokenId) when calling the DescribeStacks operation: The security token included in the request is invalid.
2017-01-30 22:11:24,895 [DEBUG] madcore: Got an error: An error occurred (InvalidClientTokenId) when calling the DescribeStacks operation: The security token included in the request is invalid.
2017-01-30 22:11:24,896 [DEBUG] madcore: Traceback (most recent call last):
  File "/home/polfilm/.local/lib/python2.7/site-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/polfilm/.local/lib/python2.7/site-packages/cliff/display.py", line 112, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/madcore-0.3.7.29+gab88154-py2.7.egg/madcore/cmds/destroy.py", line 28, in take_action
    all_stacks = self.cf_client.describe_stacks()
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.5.3-py2.7.egg/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.5.3-py2.7.egg/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidClientTokenId) when calling the DescribeStacks operation: The security token included in the request is invalid.
```

**Comment by botzill** [comment]
Again, why this issue is on core repo ? Should be on CLI.

**Comment by botzill** [comment]
Can you give me more details about this issue? How can we reproduce it ?
